-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 16:19:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_hotel` DEFAULT CHARACTER SET utf8 ;
USE `bd_hotel` ;

-- -----------------------------------------------------
-- Table `bd_hotel`.`gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_hotel`.`gerente` ;

CREATE TABLE IF NOT EXISTS `bd_hotel`.`gerente` (
  `id_gerente` INT NOT NULL AUTO_INCREMENT,
  `nivel_acesso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_gerente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_hotel`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_hotel`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `bd_hotel`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `salario` INT NULL,
  `gerente_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_gerente1_idx` (`gerente_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_gerente1`
    FOREIGN KEY (`gerente_id_usuario`)
    REFERENCES `bd_hotel`.`gerente` (`id_gerente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_hotel`.`hospede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_hotel`.`hospede` ;

CREATE TABLE IF NOT EXISTS `bd_hotel`.`hospede` (
  `id_hospede` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `documento` INT NULL,
  PRIMARY KEY (`id_hospede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_hotel`.`quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_hotel`.`quarto` ;

CREATE TABLE IF NOT EXISTS `bd_hotel`.`quarto` (
  `idquarto` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idquarto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_hotel`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_hotel`.`reserva` ;

CREATE TABLE IF NOT EXISTS `bd_hotel`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `data_checkin` DATE NULL,
  `data_checkout` DATE NULL,
  `quarto` INT NULL,
  `hospede` VARCHAR(45) NULL,
  `funcionario` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `valor_total` DOUBLE NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `hospede_id_hospede` INT NOT NULL,
  `quarto_idquarto` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_funcionario_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  INDEX `fk_reserva_hospede1_idx` (`hospede_id_hospede` ASC) VISIBLE,
  INDEX `fk_reserva_quarto1_idx` (`quarto_idquarto` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_funcionario`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `bd_hotel`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_hospede1`
    FOREIGN KEY (`hospede_id_hospede`)
    REFERENCES `bd_hotel`.`hospede` (`id_hospede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_quarto1`
    FOREIGN KEY (`quarto_idquarto`)
    REFERENCES `bd_hotel`.`quarto` (`idquarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
